version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: lexic-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./data:/mlflow/data
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlruns/mlflow.db
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0
      --port 5000
    networks:
      - lexic-network

  app:
    build: .
    container_name: lexic-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
      - ./agents:/app/agents
      - ./evals:/app/evals
      - ./shared:/app/shared
      - ./synthetic_data:/app/synthetic_data
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-claude-3-5-sonnet-20241022}
      - EXTRACTION_MODEL=${EXTRACTION_MODEL:-claude-3-5-sonnet-20241022}
      - GENERATION_MODEL=${GENERATION_MODEL:-claude-3-5-sonnet-20241022}
      - JUDGE_MODEL=${JUDGE_MODEL:-claude-3-5-sonnet-20241022}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_EXPERIMENT_NAME=${MLFLOW_EXPERIMENT_NAME:-lexic-evaluation}
    depends_on:
      - mlflow
    networks:
      - lexic-network
    profiles:
      - production

networks:
  lexic-network:
    driver: bridge

volumes:
  mlruns:
  data:
